[package]
name = "jammees/threader"
description = "Promise based Actor wrapper."
license = "MIT"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs", "test", "vendors", "package-lock.json", "package.json"]
authors = ["jammees"]

[dependencies]
Promise = "evaera/promise@4.0.0"